Alterando steps do workflow

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -12,6 +12,11 @@ jobs:
     steps:
     - name: Checkout code
       uses: actions/checkout@v3
+    
+    - name: Use .NET SDK 8.0.303
+      uses: actions/setup-dotnet@v4
+      with:
+        dotnet-version: "8.0.303"
 
     - name: Set up SSH
       uses: webfactory/ssh-agent@v0.5.3
@@ -27,10 +32,16 @@ jobs:
     - name: Copy files to VPS
       run: scp -r ./* root@191.101.18.75:/app-mtfu
 
-    - name: Run Docker Compose on VPS
+    - name: SSH and build containers to VPS
       run: |
-          ssh -o StrictHostKeyChecking=no root@191.101.18.75 '
-          cd /app-mtfu &&
-          docker compose -f ./docker-compose.yml up -d --no-deps --build
-          '
-
+        ssh root@191.101.18.75 << 'EOF'
+          cd /app-mtfu
+          if [ ! -f ".first_build_done" ]; then
+            docker-compose build || { echo "Build failed"; exit 1; }
+            docker-compose up -d || { echo "Failed to start containers"; exit 1; }
+            touch .first_build_done
+          else
+            docker-compose build api || { echo "API build failed"; exit 1; }
+            docker-compose up -d api || { echo "Failed to start API container"; exit 1; }
+          fi
+        EOF
